#!/usr/bin/env bash
#this is script
if [ -e "school" ];then
echo "school file exists"
else
echo "school file does not exist"
fi
 if [ -s "shcool" ]; then
   echo "school file does not exist"
 else
 
	 echo "school file is not empty"

 fi
 
 if [ -f "school" ]; then
      echo "school is a regular file"
fi
