#!/usr/bin/env bash
#this is script
FILE="school"
if [ -e "$FILE" ];then
echo "school file exists"
if [ -f "$FILE" ];then 
	echo " is a regular file"
fi
if [ -s "$FILE" ]; then 
	echo "school file is empty"
else
	echo "school file is not empty"
fi
else 
	echo "school file does not exist"

fi
