#!/usr/bin/env bash 
#this is script 
pid="/var/run/my_process.pid"
process="./manage_my_process"
case "$1" in 
start)
$process & 
pid=$!
echo $pid > "$PIDFILE"
echo "manage_my_process started"
;;
stop)
if [ -f "$PIDFILE" ];then
pid=$(cat "$PIDFILE")
kill "$pid" 2>/dev/null
rm -f "$PIDFILE"
  echo "manage_my_process stopped"
else

   echo "manage_my_process stopped" 
fi
;;
restart)
if [ -f "$PIDFILE" ]; then
     PID=$(cat "$PIDFILE")
     kill "$PID" 2>/dev/null
       rm -f "$PIDFILE"
fi
    
    $PROCESS &
    PID=$!
echo $PID > "$PIDFILE"
echo "manage_my_process restarted"
i;; 
*)
 echo "Usage: manage_my_process {start|stop|restart}"
;;
ecas
